
1.Go to the current folder and open command prompt
2.Run: npx create-react-app project001  (Build a React app command)
                  Or
     : npm install --global create-react-app
       create-react-app projectName
     : npm start or yarn start
 .To deploy on Surge first create the build folder using
     : npm run build or yarn build
  then deploy the index.html present on build folder in SURGE

3.Run: npm start on VS code terminal    (Open app on browser)
4.Add code from local machine to git repositary
 COMMANDS:
 Initialization of git in your repo:    git init
 Add diectory to the git staging area:  git add .
 Initial Commit:                        git commit -m "Initial Commit"
 Where push the code to github repo:    git remote add origin <url of github repo> 
 Verification of the git repo:          git remote -v
 Push the code:                         git push -u origin master
RESOLVE fail to push some refs :git pull --rebase origin master

To Update some content on a Project & Commit, Push on Git
 Show the current status:               git status
 Find out the changings: 		git diff
 Add folder to the git staging area:    git add .
 Then Commit the changes: 		git commit -m "message"
 Push the Code: 			git push

5.Workflow/actions Command:
# This is a basic workflow to help you get started with Actions

name: Deploying React App using SURGE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 12
    
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    
    - name: Build React App
      run: yarn build
      
    - name: Install Surge
      run: npm install --global surge
      
    - name: Deploy to Surge
      run: surge ./build http://react-project-prac.surge.sh/ --token ${{secrets.token3}}
